Feat/pull request
stack-spot/stackspot-workflows-action pull request #64
Opened 2023-05-10 18:30 UTC by pedrohrfz

2023-05-10 18:55 UTC, christianoguedes commented on .github/workflows/create.yml
> +          repository: ${{ fromJson(inputs.config).origin_repository }}
Não seria esse repo Pedro.
Esse é o repo de origem do reusable workkflow não o do usuário.
O repo do usuário aqui é o `https://github.com/${{ steps.checkout_user_repo.outputs.repo }}`

2023-05-10 18:57 UTC, christianoguedes commented on .github/workflows/create.yml
> +          repository: ${{ fromJson(inputs.config).origin_repository }}
é um output do step de checkout.. pq nesse step verifica se já existe o repo ou se foi criado pela action

2023-05-10 18:59 UTC, christianoguedes commented on .github/workflows/create.yml
> +              "base": "main"
```suggestion
              "base": "{{fromJson(inputs.config).default_branch}}"
```

2023-05-10 18:59 UTC, christianoguedes requested changes
little details

2023-05-10 19:00 UTC, christianoguedes requested changes
little details

2023-05-10 19:00 UTC, christianoguedes requested changes
little details

2023-05-10 19:39 UTC, christianoguedes approved these changes

2023-05-15 18:04 UTC, fabianofernandeszup approved these changes

2023-05-15 18:04 UTC, merged